In [1]:
import numpy as np
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [2]:
type(A)

numpy.ndarray

In [3]:
A.ndim

2

In [4]:
A.shape

(2, 2)

In [5]:
A.dtype

dtype('int32')

In [6]:
A[0]

array([1, 2])

In [7]:
A[1]

array([3, 4])

In [8]:
A[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [10]:
print(A[0][0], A[0][1], A[1][0], A[1][1])

1 2 3 4


In [11]:
print(A[A>1])

[2 3 4]


In [12]:
A = A.T
print(A)

[[1 3]
 [2 4]]


In [14]:
print(A.flatten())

[1 3 2 4]


In [15]:
A = A.T

In [20]:
print(A+A)
print(A-A)
print(A*A)
print(A/A)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[1. 1.]
 [1. 1.]]


In [22]:
B = np.array([10,100])
print(B)

[ 10 100]


In [23]:
print(A*B)

[[ 10 200]
 [ 30 400]]


In [24]:
B.dot(B)

10100

In [25]:
A.dot(B)

array([210, 430])

In [26]:
print(A.dot(B))

[210 430]


In [27]:
C = A.dot(B)